accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index2, name='index2'),
    url(r'^new$', views.new, name='new'),
    url(r'^create$', views.create, name='create'),
    url(r'^login$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^first-login$', login, {'template_name': 'accounts/first_login.html'}, name='thankslogin'),
    url(r'logout$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
]

main/urls.py
from django.conf.urls import url, patterns
from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.delete, name='delete'),
    url(r'^deleteall', views.deleteall, name='deleteall'),
]

shoppinglist/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('main.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Stuff(models.Model):
    title = models.CharField(max_length=100)
    user = models.CharField(default=User, max_length=100)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.http import require_POST

from .forms import RegisterForm


@login_required
def index2(request):
    return render(request, 'accounts/login.html')


def new(request):
    form = RegisterForm(request.POST or None)
    content = {'form': form,}
    return render(request, 'accounts/new.html', content)


@require_POST
def create(request):
    form = RegisterForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('accounts:thankslogin')
    content = {'form': form, }
    return render(request, 'accounts/new.html', content)

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from django.forms import ModelForm

from .models import Stuff


class StuffForm(ModelForm):
    class Meta:
        model = Stuff
        fields = ('title',)


def index(request):
    if request.user.is_active:
        stuff = Stuff.objects.filter(user=request.user)
        form = StuffForm(request.POST)
        if request.method == "POST":
            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user
                form.save()
                return redirect('main:index')
        return render(request, 'main/index.html', {'form': form, 'stuff': stuff, })
    else:
        return render(request, 'main/welcome.html')


def delete(request, pk):
    Stuff.objects.filter(id=pk).delete()
    return redirect('main:index')


def deleteall(request):
    Stuff.objects.filter(user=request.user).delete()
    return redirect('main:index')

accounts/templates/accounts/first_login.html
{% extends 'main/base.html' %}
{% block content %}
<div class="loginSignup">
    <div class="alert alert-primary" role="alert">
    Thank you!!!<br> We successfully made your new account<br>So now Let's log in and use it!
    </div>
    <h4>Log in</h4>
    <br>
    <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <labal for="username">UserName</labal><br>
            {{ form.username }}
        </div>
        <div class="form-group">
            <labal for="password">Password</labal><br>
            {{ form.password }}
        </div>
        <input type="submit" class="btn btn-info" value="Login">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'main/base.html' %}
{% block content %}
<div class="loginSignup">
    <h4>Log in</h4>
    <br>
    <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <labal for="username">UserName</labal><br>
            {{ form.username }}
        </div>
        <div class="form-group">
            <labal for="password">Password</labal><br>
            {{ form.password }}
        </div>
        <input type="submit" class="btn btn-info" value="Login">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'main/base.html' %}
{% block jump %}
<META http-equiv="Refresh" content="1;URL=/">
{% endblock %}
{% block content %}
<div id="forLogout">
    <div class="alert alert-danger" role="alert">
        You did log out
    </div>
    <a href="/">TOP</a>
</div>
{% endblock %}

accounts/templates/accounts/new.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="loginSignup">
        <h4>Create new account</h4>
        <br>
        <form method="POST" action="{% url 'accounts:create' %}">
            {% csrf_token %}
            <div class="form-group">
                <labal for="username">UserName</labal>
                {{ form.username }}
                {{ form.username.errors }}
                <small class="form-text text-muted">Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
            </div>
            <div class="form-group">
                <labal for="pass1">Password</labal>
                {{ form.password1 }}
                {{ form.password1.errors }}
                <p class="help-block">{{ form.password1.help_text }}</p>
            </div>
            <div class="form-group">
                <labal for="pass2">Password (confirm)</labal>
                {{ form.password2 }}
                {{ form.password2.errors }}
                <small class="form-text text-muted">Enter the same password as before, for verification.</small>
            </div>
            <input type="submit" class="btn btn-info" value="SIGN UP" />
        </form>
    </div>
{% endblock %}

main/templates/main/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block jump %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/original.css' %}" type="text/css">
    <link rel="shortcut icon" href="{% static 'images/f.ico' %}">
    <link rel="apple-touch-icon" sizes="128x128" href="{% static 'images/f.png' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <title>To-Buy</title>
</head>
<body>
    {% block nav %}{% endblock %}
    <div class="container">
        {% block content %}
            {{ content }}
        {% endblock %}
    </div>
    {% block Fnav %}{% endblock %}
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block nav %}
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand h1" href="/">Your shopping list</a>
        <div>
        <span style="padding-right: 10px;" class="navbar-text">
            log in as || {{ request.user }} ||
        </span>
        <form action="{% url 'accounts:logout' %}" style="float: right;">
            <input class="btn btn btn-outline-info" type="submit" value="Log out" />
        </form>
        </div>
    </nav>
{% endblock %}
{% block content %}

    <hr />
    <form style="text-align: right" action="{% url 'main:index' %}" method="post">
        {% csrf_token %}
        {{ form.title }}
        <input type="submit" value='ADD TO LIST' class="btn btn-info" />
    </form>
    <br />
        {% for s in stuff %}
            <ul class="list-group">
                <li class="list-group-item">

                    <form action="{% url 'main:delete' s.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="BOUGHT" class="btn btn-primary" />
                    </form>
                    <h3>{{ s.title }}</h3>
                </li>
            </ul>
        {% endfor %}
    <br />
    <form method="post" action="{% url 'main:deleteall' %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-outline-secondary btn-lg btn-block" value="DELETE ALL" />
    </form>
{% endblock %}
{% block Fnav %}
    <nav class="navbar fixed-bottom navbar-dark bg-dark">

    </nav>
{% endblock %}

main/templates/main/welcome.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/original.css' %}" type="text/css">
    <link rel="shortcut icon" href="{% static 'images/f.ico' %}">
    <link rel="apple-touch-icon" sizes="128x128" href="{% static 'images/f.png' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <title>To-Buy</title>
</head>
<body style="background: #323a45;">
    {% block nav %}{% endblock %}
    <div id="welcome" class="container">
        <img src="{{ 'static/images/top.jpg' }}" alt="" width="800px"/>

        <div style="padding-top: 300px">
            <form action="{% url 'accounts:login' %}" style="margin-bottom: 50px">
                <input class="btn btn-info" type="submit" value="Log in" />
            </form>
            <form action="{% url 'accounts:new' %}">
                <input class="btn btn-info" type="submit" value="Sign up" />
            </form>
        </div>
    </div>
</body>
</html>